apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-atlassian-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/atlassian@sha256:00ce6c4fe143ae63c28e30dd58b7e913ca1bb9dee34330fa4521b9c94b0d7d90"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "atlassian-mcp-secrets"
