apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-box-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/box@sha256:4db7963505c2ea80c0f8c867e7062f74d96c839687f1b79cedb3836a74498656"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "box-mcp-secrets"
