apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-chroma-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/chroma@sha256:c050ca8e1d4e258dd66649fc91acbc77615ce4b89bbc18281a985932bd9c9874"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "chroma-mcp-secrets"
