apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-context7-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/context7@sha256:1174e6a29634a83b2be93ac1fefabf63265f498c02c72201fe3464e687dd8836"
      imagePullPolicy: IfNotPresent
  mcp:
    initClientCapabilities: {}
