apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-github-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "ghcr.io/github/github-mcp-server@sha256:d909564772c4afc7ed08831c1fce367c051d82f8602abc4c1f033cdfc4a89e68"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "github-mcp-secrets"
