apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-markitdown-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/markitdown@sha256:a93f01634ef919fae708b3c173f88785e6c586d9e485fef0a2bb15363f29cc1d"
      imagePullPolicy: IfNotPresent
  mcp:
    initClientCapabilities: {}
