apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-neon-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/neon@sha256:fab32eb73fb01e858b1effecc735c907488ba42536f7498e034b0567729051de"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "neon-mcp-secrets"
