apiVersion: bubustack.io/v1alpha1
kind: Engram
metadata:
  name: "mcp-postman-stdio"
  namespace: default
spec:
  mode: job
  templateRef:
    name: "mcp-adapter"
  overrides:
    serviceAccountName: "mcp-adapter-sa"
  with:
    transport: stdio
    stdio:
      image: "docker.io/mcp/postman@sha256:53fb05f7a2f053e56ca6b007825eb2aae45895ebff7ab0695694d204504b5df4"
      imagePullPolicy: IfNotPresent
      useEphemeralSecret: true
  mcp:
    initClientCapabilities: {}
  secrets:
    server: "postman-mcp-secrets"
